<?xml version="1.0" ?>
<testsuite errors="1" failures="1" name="tuqquery.flex_index_phase1.FlexIndexTests" skip="0" tests="1" time="1383.4468867778778">
	<testcase name="tuqquery.flex_index_phase1.FlexIndexTests.test_flex_single_typemapping_partial_sargability,GROUP:PS,get-logs:False,stop-on-failure:False,doc-per-day:6,bucket_size:200,scan_consistency:NOT_BOUNDED,skip_load:True,items:1000,custom_map:True,get-cbcollect-info:False,disable_HTP:True,cluster:D+F,index_type:scorch,fts_quota:750,custom_map_add_non_indexed_fields:False,text_analyzer:keyword,use_index_name_in_query:False,ini:test.ini,cluster_name:test,spec:test,conf_file:test.conf,num_nodes:4,case_number:1,logs_folder:/Users/girishbenakappa/IdeaProjects/testrunner/logs/testrunner-20-Apr-27_13-15-47/test_1" time="1383.4468867778778">
		<error type="membase.error">['Traceback (most recent call last):\n  File &quot;pytests/tuqquery/flex_index_phase1.py&quot;, line 244, in test_flex_single_typemapping_partial_sargability\n    gsi_fields = self.get_gsi_fields_partial_sargability(fts_index)\nTypeError: get_gsi_fields_partial_sargability() takes 1 positional argument but 2 were given\n']</error>
	</testcase>
</testsuite>
