[2019-04-26 23:04:44,836] - [fts_base] [123145410170880] - INFO - ==== FTSbasetests setup is started for test #2 check_fts_service_started ====
[2019-04-26 23:04:44,849] - [fts_base] [123145410170880] - INFO - removing nodes from cluster ...
[2019-04-26 23:04:44,860] - [fts_base] [123145410170880] - INFO - cleanup [ip:192.168.10.12 port:8091 ssh_username:root]
[2019-04-26 23:04:44,898] - [cluster_helper] [123145410170880] - INFO - waiting for ns_server @ 192.168.10.12:8091
[2019-04-26 23:04:44,903] - [cluster_helper] [123145410170880] - INFO - ns_server @ 192.168.10.12:8091 is running
[2019-04-26 23:04:44,904] - [fts_base] [123145410170880] - INFO - Removing user 'cbadminbucket'...
[2019-04-26 23:04:44,917] - [rest_client] [123145410170880] - ERROR - DELETE http://192.168.10.12:8091/settings/rbac/users/local/cbadminbucket body:  headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Accept': '*/*', 'Authorization': 'Basic QWRtaW5pc3RyYXRvcjpQYXNzdzByZA==\n'} error: 404 reason: unknown "User was not found." auth: Administrator:Passw0rd
[2019-04-26 23:04:44,917] - [fts_base] [123145410170880] - INFO - "User was not found."
[2019-04-26 23:04:44,918] - [fts_base] [123145410170880] - INFO - Initializing Cluster ...
[2019-04-26 23:04:45,851] - [task] [123145435410432] - INFO - server: ip:192.168.10.12 port:8091 ssh_username:root, nodes/self: {'ip': u'192.168.10.12', 'availableStorage': [], 'rest_username': '', 'id': u'ns_1@192.168.10.12', 'uptime': u'151', 'mcdMemoryReserved': 3032, 'storageTotalRam': 3790, 'hostname': u'192.168.10.12:8091', 'storage': [<membase.api.rest_client.NodeDataStorage object at 0x10533a490>], 'moxi': 11211, 'port': u'8091', 'version': u'6.5.0-3068-enterprise', 'memcached': 11210, 'status': u'healthy', 'clusterCompatibility': 393221, 'curr_items': 0, 'services': [u'index', u'kv', u'n1ql'], 'rest_password': '', 'clusterMembership': u'active', 'memoryFree': 3413262336, 'memoryTotal': 3974823936, 'memoryQuota': 2021, 'mcdMemoryAllocated': 3032, 'os': u'x86_64-unknown-linux-gnu', 'ports': []}
[2019-04-26 23:04:45,858] - [rest_client] [123145435410432] - INFO - pools/default params : memoryQuota=2021
[2019-04-26 23:04:45,865] - [rest_client] [123145435410432] - INFO - settings/web params on 192.168.10.12:8091:username=Administrator&password=Passw0rd&port=8091
[2019-04-26 23:04:45,904] - [remote_util] [123145435410432] - INFO - connecting to 192.168.10.12 with username:root 
[2019-04-26 23:04:46,076] - [remote_util] [123145435410432] - INFO - Connected to 192.168.10.12
[2019-04-26 23:04:46,302] - [remote_util] [123145435410432] - INFO - It could be other operating system.  Go to check at other location
[2019-04-26 23:04:46,732] - [remote_util] [123145435410432] - INFO - running command.raw on 192.168.10.12: curl http://Administrator:Passw0rd@localhost:8091/diag/eval -X POST -d 'ns_config:set(allow_nonlocal_eval, true).'
[2019-04-26 23:04:46,787] - [remote_util] [123145435410432] - INFO - command executed successfully
[2019-04-26 23:04:46,791] - [rest_client] [123145435410432] - INFO - /diag/eval status on 192.168.10.12:8091: True content: [6,5] command: cluster_compat_mode:get_compat_version().
[2019-04-26 23:04:46,792] - [rest_client] [123145435410432] - INFO - settings/indexes params : storageMode=forestdb
[2019-04-26 23:04:46,797] - [rest_client] [123145435410432] - ERROR - POST http://192.168.10.12:8091/settings/indexes body: storageMode=forestdb headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Accept': '*/*', 'Authorization': 'Basic QWRtaW5pc3RyYXRvcjpQYXNzdzByZA==\n'} error: 400 reason: unknown {"errors":{"storageMode":"The value must be one of the following: [plasma,memory_optimized]"}} auth: Administrator:Passw0rd
[2019-04-26 23:04:46,807] - [fts_base] [123145410170880] - INFO - 192.168.10.11 will be configured with services kv,fts
[2019-04-26 23:04:46,808] - [fts_base] [123145410170880] - INFO - 192.168.10.13 will be configured with services fts
[2019-04-26 23:04:47,812] - [task] [123145435410432] - INFO - adding node 192.168.10.11:8091 to cluster
[2019-04-26 23:04:47,812] - [rest_client] [123145435410432] - INFO - adding remote node @192.168.10.11:8091 to this cluster @192.168.10.12:8091
[2019-04-26 23:04:49,449] - [task] [123145435410432] - INFO - adding node 192.168.10.13:8091 to cluster
[2019-04-26 23:04:49,450] - [rest_client] [123145435410432] - INFO - adding remote node @192.168.10.13:8091 to this cluster @192.168.10.12:8091
[2019-04-26 23:04:51,207] - [rest_client] [123145435410432] - INFO - rebalance params : {'password': 'Passw0rd', 'ejectedNodes': '', 'user': 'Administrator', 'knownNodes': u'ns_1@192.168.10.11,ns_1@192.168.10.12,ns_1@192.168.10.13'}
[2019-04-26 23:04:51,215] - [rest_client] [123145435410432] - INFO - rebalance operation started
[2019-04-26 23:04:51,221] - [rest_client] [123145435410432] - INFO - rebalance percentage : 0.00 %
[2019-04-26 23:04:51,222] - [task] [123145435410432] - INFO - Rebalance - status: running, progress: 0.00%
[2019-04-26 23:05:01,272] - [task] [123145435410432] - INFO - Rebalance - status: none, progress: 100.00%
[2019-04-26 23:05:01,280] - [task] [123145435410432] - INFO - rebalancing was completed with progress: 100% in 10.0638480186 sec
[2019-04-26 23:05:01,291] - [remote_util] [123145410170880] - INFO - connecting to 192.168.10.12 with username:root 
[2019-04-26 23:05:01,440] - [remote_util] [123145410170880] - INFO - Connected to 192.168.10.12
[2019-04-26 23:05:01,697] - [remote_util] [123145410170880] - INFO - It could be other operating system.  Go to check at other location
[2019-04-26 23:05:02,095] - [remote_util] [123145410170880] - INFO - running command.raw on 192.168.10.12: curl http://Administrator:Passw0rd@localhost:8091/diag/eval -X POST -d 'ns_config:set(allow_nonlocal_eval, true).'
[2019-04-26 23:05:02,165] - [remote_util] [123145410170880] - INFO - command executed successfully
[2019-04-26 23:05:02,166] - [fts_base] [123145410170880] - INFO - Enabled diag/eval for non-local hosts from 192.168.10.12
[2019-04-26 23:05:02,194] - [rest_client] [123145410170880] - ERROR - DELETE http://192.168.10.12:8091/settings/rbac/users/local/cbadminbucket body:  headers: {'Content-Type': 'application/x-www-form-urlencoded', 'Accept': '*/*', 'Authorization': 'Basic QWRtaW5pc3RyYXRvcjpQYXNzdzByZA==\n'} error: 404 reason: unknown "User was not found." auth: Administrator:Passw0rd
[2019-04-26 23:05:02,195] - [internal_user] [123145410170880] - INFO - Exception while deleting user. Exception is -"User was not found."
[2019-04-26 23:05:02,310] - [rest_client] [123145435410432] - INFO - http://192.168.10.12:8091/pools/default/buckets with param: bucketType=membase&evictionPolicy=valueOnly&threadsNumber=3&ramQuotaMB=1521&authType=sasl&name=sasl_bucket_1&flushEnabled=1&replicaNumber=1&compressionMode=passive&saslPassword=password&replicaIndex=1
[2019-04-26 23:05:02,319] - [rest_client] [123145435410432] - INFO - 0.01 seconds to create bucket sasl_bucket_1
[2019-04-26 23:05:02,320] - [bucket_helper] [123145435410432] - INFO - waiting for memcached bucket : sasl_bucket_1 in 192.168.10.12 to accept set ops
[2019-04-26 23:05:04,031] - [data_helper] [123145435410432] - INFO - creating direct client 192.168.10.11:11210 sasl_bucket_1
[2019-04-26 23:05:04,162] - [data_helper] [123145435410432] - INFO - creating direct client 192.168.10.12:11210 sasl_bucket_1
[2019-04-26 23:05:04,446] - [data_helper] [123145435410432] - INFO - creating direct client 192.168.10.11:11210 sasl_bucket_1
[2019-04-26 23:05:04,531] - [data_helper] [123145435410432] - INFO - creating direct client 192.168.10.12:11210 sasl_bucket_1
[2019-04-26 23:05:04,811] - [task] [123145435410432] - INFO - bucket 'sasl_bucket_1' was created with per node RAM quota: 1521
[2019-04-26 23:05:04,819] - [rest_client] [123145410170880] - INFO - /diag/eval status on 192.168.10.12:8091: True content: "/opt/couchbase/var/lib/couchbase/logs" command: filename:absname(element(2, application:get_env(ns_server,error_logger_mf_dir))).
[2019-04-26 23:05:04,820] - [remote_util] [123145410170880] - INFO - connecting to 192.168.10.12 with username:root 
[2019-04-26 23:05:04,969] - [remote_util] [123145410170880] - INFO - Connected to 192.168.10.12
[2019-04-26 23:05:05,184] - [remote_util] [123145410170880] - INFO - It could be other operating system.  Go to check at other location
[2019-04-26 23:05:05,534] - [remote_util] [123145410170880] - INFO - running command.raw on 192.168.10.12: zgrep "panic:" "/opt/couchbase/var/lib/couchbase/logs"/fts.log* | wc -l
[2019-04-26 23:05:05,588] - [remote_util] [123145410170880] - INFO - command executed successfully
[2019-04-26 23:05:05,589] - [fts_base] [123145410170880] - INFO - 0
[2019-04-26 23:05:05,715] - [remote_util] [123145410170880] - INFO - connecting to 192.168.10.11 with username:root 
[2019-04-26 23:05:05,869] - [remote_util] [123145410170880] - INFO - Connected to 192.168.10.11
[2019-04-26 23:05:06,095] - [remote_util] [123145410170880] - INFO - It could be other operating system.  Go to check at other location
[2019-04-26 23:05:06,477] - [remote_util] [123145410170880] - INFO - running command.raw on 192.168.10.11: zgrep "panic:" "/opt/couchbase/var/lib/couchbase/logs"/fts.log* | wc -l
[2019-04-26 23:05:06,553] - [remote_util] [123145410170880] - INFO - command executed successfully
[2019-04-26 23:05:06,554] - [fts_base] [123145410170880] - INFO - 0
[2019-04-26 23:05:06,679] - [remote_util] [123145410170880] - INFO - connecting to 192.168.10.13 with username:root 
[2019-04-26 23:05:06,846] - [remote_util] [123145410170880] - INFO - Connected to 192.168.10.13
[2019-04-26 23:05:07,101] - [remote_util] [123145410170880] - INFO - It could be other operating system.  Go to check at other location
[2019-04-26 23:05:07,524] - [remote_util] [123145410170880] - INFO - running command.raw on 192.168.10.13: zgrep "panic:" "/opt/couchbase/var/lib/couchbase/logs"/fts.log* | wc -l
[2019-04-26 23:05:07,628] - [remote_util] [123145410170880] - INFO - command executed successfully
[2019-04-26 23:05:07,629] - [fts_base] [123145410170880] - INFO - 0
[2019-04-26 23:05:07,754] - [fts_base] [123145410170880] - INFO - {'192.168.10.12': {'panic:': 0}, '192.168.10.13': {'panic:': 0}, '192.168.10.11': {'panic:': 0}}
[2019-04-26 23:05:07,755] - [fts_base] [123145410170880] - INFO - ==== FTSbasetests setup is finished for test #2 check_fts_service_started ====
[2019-04-26 23:05:07,779] - [rest_client] [123145410170880] - ERROR - GET http://192.168.10.11:8094/api/index/invalid_index body:  headers: {'Content-Type': 'application/json', 'Accept': '*/*', 'Authorization': 'Basic QWRtaW5pc3RyYXRvcjpQYXNzdzByZA==\n'} error: 400 reason: rest_auth: preparePerms, err: index not found {"error":"rest_auth: preparePerms, err: index not found","request":"","status":"fail"} auth: Administrator:Passw0rd
[2019-04-26 23:05:07,789] - [rest_client] [123145410170880] - INFO - /diag/eval status on 192.168.10.12:8091: True content: "/opt/couchbase/var/lib/couchbase/logs" command: filename:absname(element(2, application:get_env(ns_server,error_logger_mf_dir))).
[2019-04-26 23:05:07,790] - [remote_util] [123145410170880] - INFO - connecting to 192.168.10.12 with username:root 
[2019-04-26 23:05:07,939] - [remote_util] [123145410170880] - INFO - Connected to 192.168.10.12
[2019-04-26 23:05:08,200] - [remote_util] [123145410170880] - INFO - It could be other operating system.  Go to check at other location
[2019-04-26 23:05:08,544] - [remote_util] [123145410170880] - INFO - running command.raw on 192.168.10.12: zgrep "panic:" "/opt/couchbase/var/lib/couchbase/logs"/fts.log* | wc -l
[2019-04-26 23:05:08,599] - [remote_util] [123145410170880] - INFO - command executed successfully
[2019-04-26 23:05:08,600] - [fts_base] [123145410170880] - INFO - 0
[2019-04-26 23:05:08,601] - [fts_base] [123145410170880] - INFO - Initial 'panic:' count on 192.168.10.12 :0, now :0
[2019-04-26 23:05:08,730] - [remote_util] [123145410170880] - INFO - connecting to 192.168.10.11 with username:root 
[2019-04-26 23:05:08,883] - [remote_util] [123145410170880] - INFO - Connected to 192.168.10.11
[2019-04-26 23:05:09,171] - [remote_util] [123145410170880] - INFO - It could be other operating system.  Go to check at other location
[2019-04-26 23:05:09,519] - [remote_util] [123145410170880] - INFO - running command.raw on 192.168.10.11: zgrep "panic:" "/opt/couchbase/var/lib/couchbase/logs"/fts.log* | wc -l
[2019-04-26 23:05:09,620] - [remote_util] [123145410170880] - INFO - command executed successfully
[2019-04-26 23:05:09,621] - [fts_base] [123145410170880] - INFO - 0
[2019-04-26 23:05:09,622] - [fts_base] [123145410170880] - INFO - Initial 'panic:' count on 192.168.10.11 :0, now :0
[2019-04-26 23:05:09,746] - [remote_util] [123145410170880] - INFO - connecting to 192.168.10.13 with username:root 
[2019-04-26 23:05:09,921] - [remote_util] [123145410170880] - INFO - Connected to 192.168.10.13
[2019-04-26 23:05:10,215] - [remote_util] [123145410170880] - INFO - It could be other operating system.  Go to check at other location
[2019-04-26 23:05:10,595] - [remote_util] [123145410170880] - INFO - running command.raw on 192.168.10.13: zgrep "panic:" "/opt/couchbase/var/lib/couchbase/logs"/fts.log* | wc -l
[2019-04-26 23:05:10,697] - [remote_util] [123145410170880] - INFO - command executed successfully
[2019-04-26 23:05:10,697] - [fts_base] [123145410170880] - INFO - 0
[2019-04-26 23:05:10,698] - [fts_base] [123145410170880] - INFO - Initial 'panic:' count on 192.168.10.13 :0, now :0
[2019-04-26 23:05:10,822] - [fts_base] [123145410170880] - INFO - ====  FTSbasetests cleanup is started for test #2 check_fts_service_started ====
[2019-04-26 23:05:10,823] - [fts_base] [123145410170880] - INFO - removing nodes from cluster ...
[2019-04-26 23:05:10,835] - [fts_base] [123145410170880] - INFO - cleanup [ip:192.168.10.12 port:8091 ssh_username:root, ip:192.168.10.11 port:8091 ssh_username:root, ip:192.168.10.13 port:8091 ssh_username:root]
[2019-04-26 23:05:10,855] - [bucket_helper] [123145410170880] - INFO - deleting existing buckets [u'sasl_bucket_1'] on 192.168.10.12
[2019-04-26 23:05:10,856] - [bucket_helper] [123145410170880] - INFO - remove bucket sasl_bucket_1 ...
[2019-04-26 23:05:11,825] - [bucket_helper] [123145410170880] - INFO - deleted bucket : sasl_bucket_1 from 192.168.10.12
[2019-04-26 23:05:11,825] - [bucket_helper] [123145410170880] - INFO - waiting for bucket deletion to complete....
[2019-04-26 23:05:11,830] - [rest_client] [123145410170880] - INFO - node 192.168.10.12 existing buckets : []
[2019-04-26 23:05:11,831] - [bucket_helper] [123145410170880] - INFO - sleep 2 seconds to make sure all buckets ([u'sasl_bucket_1']) were deleted completely.
[2019-04-26 23:05:13,861] - [cluster_helper] [123145410170880] - INFO - rebalancing all nodes in order to remove nodes
[2019-04-26 23:05:13,866] - [rest_client] [123145410170880] - INFO - rebalance params : {'password': 'Passw0rd', 'ejectedNodes': u'ns_1@192.168.10.11,ns_1@192.168.10.13', 'user': 'Administrator', 'knownNodes': u'ns_1@192.168.10.11,ns_1@192.168.10.12,ns_1@192.168.10.13'}
[2019-04-26 23:05:13,873] - [rest_client] [123145410170880] - INFO - rebalance operation started
[2019-04-26 23:05:13,881] - [rest_client] [123145410170880] - INFO - rebalance percentage : 0.00 %
[2019-04-26 23:05:23,890] - [rest_client] [123145410170880] - INFO - rebalance percentage : 38.89 %
[2019-04-26 23:05:43,909] - [rest_client] [123145410170880] - INFO - rebalance progress took 30.04 seconds 
[2019-04-26 23:05:43,909] - [rest_client] [123145410170880] - INFO - sleep for 10 seconds after rebalance...
[2019-04-26 23:05:53,936] - [cluster_helper] [123145410170880] - INFO - removed all the nodes from cluster associated with ip:192.168.10.12 port:8091 ssh_username:root ? [(u'ns_1@192.168.10.11', 8091), (u'ns_1@192.168.10.13', 8091)]
[2019-04-26 23:05:53,942] - [cluster_helper] [123145410170880] - INFO - waiting for ns_server @ 192.168.10.12:8091
[2019-04-26 23:05:53,948] - [cluster_helper] [123145410170880] - INFO - ns_server @ 192.168.10.12:8091 is running
[2019-04-26 23:05:53,976] - [cluster_helper] [123145410170880] - INFO - waiting for ns_server @ 192.168.10.11:8091
[2019-04-26 23:05:53,981] - [cluster_helper] [123145410170880] - INFO - ns_server @ 192.168.10.11:8091 is running
[2019-04-26 23:05:54,021] - [cluster_helper] [123145410170880] - INFO - waiting for ns_server @ 192.168.10.13:8091
[2019-04-26 23:05:54,026] - [cluster_helper] [123145410170880] - INFO - ns_server @ 192.168.10.13:8091 is running
[2019-04-26 23:05:54,027] - [fts_base] [123145410170880] - INFO - Removing user 'cbadminbucket'...
[2019-04-26 23:05:54,043] - [fts_base] [123145410170880] - INFO - ====  FTSbasetests cleanup is finished for test #2 check_fts_service_started ===
